FLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

EXEC_NAME  = quadratka.exe
SOURCE_DIR = source
BUILD_DIR = build
INC_DIR = include

SOURCE_FILES = $(wildcard $(SOURCE_DIR)/*.cpp)
OBJ_FILES    = $(patsubst $(SOURCE_DIR)/%.cpp, $(BUILD_DIR)/%.o, $(SOURCE_FILES))

$(EXEC_NAME): $(OBJ_FILES)
	g++ $^ $(FLAGS) -o $@


$(BUILD_DIR)/%.o: $(SOURCE_DIR)/%.cpp
	g++ -c $(FLAGS) -I$(INC_DIR)/ $< -o $@

run: $(EXEC_NAME)
	./$(EXEC_NAME)

clean:
	rm -f $(OBJ_FILES) $(EXEC_NAME)



