FLAGS=-Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

EXEC_NAME  = quadratka.exe
SOURCE_DIR = source/
BUILD_DIR = build/
INC_DIR = include/



link: $(BUILD_DIR)main.o $(BUILD_DIR)argc.o $(BUILD_DIR)solve_square.o $(BUILD_DIR)unit_test.o $(BUILD_DIR)comparison_double.o
	g++ $(BUILD_DIR)main.o $(BUILD_DIR)argc.o $(BUILD_DIR)solve_square.o $(BUILD_DIR)unit_test.o $(BUILD_DIR)comparison_double.o -o $(EXEC_NAME)

$(BUILD_DIR)main.o: $(SOURCE_DIR)main.cpp
	g++ -c $(FLAGS) -I$(INC_DIR) $(SOURCE_DIR)main.cpp -o $(BUILD_DIR)main.o
$(BUILD_DIR)argc.o: $(SOURCE_DIR)argc.cpp
	g++ -c $(FLAGS) -I$(INC_DIR) $(SOURCE_DIR)argc.cpp -o $(BUILD_DIR)argc.o
$(BUILD_DIR)solve_square.o: $(SOURCE_DIR)solve_square.cpp
	g++ -c $(FLAGS) -I$(INC_DIR) $(SOURCE_DIR)solve_square.cpp -o $(BUILD_DIR)solve_square.o
$(BUILD_DIR)unit_test.o: $(SOURCE_DIR)unit_test.cpp
	g++ -c $(FLAGS) -I$(INC_DIR) $(SOURCE_DIR)unit_test.cpp -o $(BUILD_DIR)unit_test.o
$(BUILD_DIR)comparison_double.o: $(SOURCE_DIR)comparison_double.cpp
	g++ -c $(FLAGS) -I$(INC_DIR) $(SOURCE_DIR)comparison_double.cpp -o $(BUILD_DIR)comparison_double.o
run: $(EXEC_NAME)
	./$(EXEC_NAME)
	 

	
	 